// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcaapEDr2Az0SxWXJzr9zWyoVaH1pMwTk',
    appId: '1:756269166758:web:2a567f9ad4bb39b0b74467',
    messagingSenderId: '756269166758',
    projectId: 'notification-app-27554',
    authDomain: 'notification-app-27554.firebaseapp.com',
    storageBucket: 'notification-app-27554.firebasestorage.app',
    measurementId: 'G-LEE22LJVXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFEo1NLjHc9W270q0wlvTzS5uL5kUPjgo',
    appId: '1:756269166758:android:da890318298107fab74467',
    messagingSenderId: '756269166758',
    projectId: 'notification-app-27554',
    storageBucket: 'notification-app-27554.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKlIhWPDSIeXUna9BsF-BdPQzMo_AxtzM',
    appId: '1:756269166758:ios:b3c7befa3c877ffeb74467',
    messagingSenderId: '756269166758',
    projectId: 'notification-app-27554',
    storageBucket: 'notification-app-27554.firebasestorage.app',
    iosBundleId: 'com.example.notificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKlIhWPDSIeXUna9BsF-BdPQzMo_AxtzM',
    appId: '1:756269166758:ios:b3c7befa3c877ffeb74467',
    messagingSenderId: '756269166758',
    projectId: 'notification-app-27554',
    storageBucket: 'notification-app-27554.firebasestorage.app',
    iosBundleId: 'com.example.notificationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcaapEDr2Az0SxWXJzr9zWyoVaH1pMwTk',
    appId: '1:756269166758:web:d28f7f6d867c4b9ab74467',
    messagingSenderId: '756269166758',
    projectId: 'notification-app-27554',
    authDomain: 'notification-app-27554.firebaseapp.com',
    storageBucket: 'notification-app-27554.firebasestorage.app',
    measurementId: 'G-VFXE8SEBR5',
  );
}
